# devops/helm-charts/app/values-ce8baa-dev.yaml

# REQUIRED by templates (used to form image path + vault SA name)
OPENSHIFT_NAMESPACE: ce8baa
STAGE: dev
appName: energy-app

# If your cluster/vault setup uses a different namespace name, change this.
vaultNamespace: ce8baa-nonprod

# REQUIRED by templates (template uses $.Values.imageRepository)
imageRepository: image-registry.openshift-image-registry.svc:5000

route:
  spec:
    host: ""

# If your chart templates reference pvc.*, keep this. If not, it’s harmless but unused.
pvc:
  spec:
    resources:
      requests:
        storage: 250Mi

# These ARE used by templates (template uses $.Values.image.name and $.Values.image.tag)
image:
  name: energy-app
  tag: latest

deployments:
  - process: web
    replicaCount: 1
    spec:
      containers:
        includeCommand: false
        resources:
          requests:
            cpu: 300m
            memory: 256Mi
          limits:
            cpu: 750m
            memory: 512Mi

  - process: worker
    replicaCount: 1
    spec:
      containers:
        includeCommand: true
        args:
          - >-
            set -a; . /vault/secrets/secrets.env; set +a; exec bundle exec sidekiq
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 250m
            memory: 512Mi

  - process: anycable-rpc
    replicaCount: 1
    spec:
      containers:
        includeCommand: true
        args:
          - >-
            set -a; . /vault/secrets/secrets.env; set +a; exec bundle exec anycable --rpc-host=0.0.0.0:50051
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi